### ISSUE TITLE
Pass logoutURL to return back to previous page in WordPress

### ISSUE THREAD

**Issue by ffdixon** [blindsidenetworks/wordpress-plugin_bigbluebutton#12]
Reported in

    https://groups.google.com/d/msg/bigbluebutton-setup/OqWfDUJPspY/xlWKSFMyCgAJ

Looks like it's returning users to the wp-admin page.

**Comment by jfederico** [comment]
If they created the meeting from the admin page (which was for testing), yes, of course. 

The origin was always unknown as the meeting could have been created from any page using shortcodes.

In the new version users are returned to the room page.
