### ISSUE TITLE
Add Content-Security-Policy header when running embedded in a page with Chrome

### ISSUE THREAD

**Issue by ffdixon** [blindsidenetworks/wordpress-plugin_bigbluebutton#15]
Chrome requires a  Content-Security-Policy  to enable access to webcam and microphone when running embedded in a web page.

Reported on

  https://groups.google.com/d/msg/bigbluebutton-setup/L6RWgBK8SRY/0_kmZ9QkBAAJ

There is a very helpful video at the above link.

**Comment by jfederico** [comment]
The idea was and has been to drive users to BBB from the front page which will bring the users to a new tab, not from the admin page. The admin page was just that, a page for administrators.

Either way, this is outdated as the new version only supports Join from the front page
