### ISSUE TITLE
A not so nice error shows up when the bbb server is not correctly configured

### ISSUE THREAD

**Issue by jfederico** [blindsidenetworks/wordpress-plugin_bigbluebutton#41]
How to reproduce:

Go to Rooms/settings
Change the URL to something that is not a BBB server
Go to a Room page

The error is trigger by the getRecordings request

![Screenshot from 2019-12-13 16-13-34](https://user-images.githubusercontent.com/578359/70832664-a8709480-1dc3-11ea-9d61-a05a056cc2a3.png)

**Comment by yfngdu** [comment]
It is a warning that is shown if debug is on, which should not be the case for production environments. The feature implemented for https://github.com/blindsidenetworks/wordpress-plugin_bigbluebutton/pull/48 will ensure the settings are valid, which will diminish the rate of occurrence for this warning.
