### ISSUE TITLE
Old rooms lost after upgrading to v3

### ISSUE THREAD

**Issue by alfonsofernandezyf** [blindsidenetworks/wordpress-plugin_bigbluebutton#59]
Just update to new version, but cannot see any of the old rooms or its recordings.

**Comment by yfngdu** [comment]
Hi @alfonsofernandezyf, could you redirect your question to https://wordpress.org/support/plugin/bigbluebutton/, for support with BigBlueButton? If it does not get resolved in the support forum, please come back and re-open this issue.
