### ISSUE TITLE
Add support for thumbnails to bbb-room CPT

### ISSUE THREAD

**Issue by alfonsofernandezyf** [blindsidenetworks/wordpress-plugin_bigbluebutton#65]
I would like to add Thumbnail support for bbb-room post type. 

Think is a good Idea, I can send a pull request with the changes.

**Comment by jfederico** [comment]
Hey @alfonsofernandezyf thanks for the suggestion and also for the PR!

This is actually the way we are doing the development, we fist create the issue and then the PR, this way we keep track of what is being added. It is also easy for us to update the release notes.

One thing though. The next time you open a PR, please add a reference to the Issue like "closes #65". This way when we merge the PR, the issue closes automatically.

Thanks again

**Comment by alfonsofernandezyf** [comment]
Hi Jesus, thank you I'm very happy to help.
