### ISSUE TITLE
Plugin not working with WP5.4

### ISSUE THREAD

**Issue by glu000** [blindsidenetworks/wordpress-plugin_bigbluebutton#84]
I installed the plugin as described. Connection to BBB server is OK. I can add rooms. After publishing the room and trying to access the room-page (permalink) I get an error "page not found". 

I deactivated all other plugins - error is still the same

**Comment by jibon57** [comment]
I guess you are trying from localhost. Try to create custom domain & use it. It should work.

**Comment by emadbagheri96** [comment]
same here with host and domain, getting 404 for rooms pages
nothing works except the `join` button with shortcode

**Comment by jibon57** [comment]
Setting like this way in localhost should work.

![image](https://user-images.githubusercontent.com/6080277/80272225-3ef58080-86e9-11ea-9598-9ee0411a2738.png)

**Comment by agru** [comment]
> Setting like this way in localhost should work.

Yes - that also worked for me. Now at least the permalink works. But what do I have to enter for "Name" and "Access Code" when the user is *not* logged in? Does this work for anybody?
