### ISSUE TITLE
Name and description of the records are not saved

### ISSUE THREAD

**Issue by MrCapitalist** [blindsidenetworks/wordpress-plugin_bigbluebutton#88]
Hi
We use latest versiob of Wordpress and BBB to show records list of our classes.
In previous version I could edit name and description of every record but now:
I click on edit icon, type a name and press enter, it comes out of edit mode and It seems to be saved. But when I refresh the page, all of edits disappear! I even refresh page with Ctrl+F5 but it doesn't work :(

**Comment by albertosgz** [comment]
I don't remember to change that part.
Can you check out in network tab of developer tools what is BBB server replying?

**Comment by albertosgz** [comment]
Are you using any load balancer between the plugin and the BBB server?

**Comment by MrCapitalist** [comment]
> I don't remember to change that part.
> Can you check out in network tab of developer tools what is BBB server replying?

It send these data:

`action: set_bbb_recording_edits
post_type: POST
meta_nonce: XXXXX
record_id: XXXXX
type: description
value: test`

and get ajax 200 response

{success: true}

> Are you using any load balancer between the plugin and the BBB server?

Not now. Wordpress connect directly to BBB server

**Comment by albertosgz** [comment]
Did you change BBB version?

**Comment by MrCapitalist** [comment]
I installed Scalelite and I can change them now
